name: Cobalt Techno
favicon: null
layout_spectrum: 0.01525965123437345
typography_spectrum: 0.1343516621273011
title: Cobalt Techno - App Development from North Wales
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.12517738225869834
  lightness: 0.8132369315717369
  saturation: 0.6149970628321171
  rhythmicContrast: 0.49765251530334353
purpose: []
